sudo: required
services:
  - docker
before_install:
  - version=$(git rev-parse --short HEAD)
  - docker build -t gaga5lala/fukuball-jieba-demo:$version .
script:
  - docker images gaga5lala/fukuball-jieba-demo
# - echo "version: $version"
# - echo "# invisiable variable"
# - echo "username: $DOCKER_USERNAME"
# - echo "password: $DOCKER_PASSWORD"
after_success:
  # TODO: only master branch
  - if [ "$TRAVIS_BRANCH" == "use-travis-ci-build-docker" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push "gaga5lala/use-travis-ci-build-docker:$version";
    fi
