sudo: required
services:
  - docker
before_install:
  - version=$(git rev-parse --short HEAD)
  - docker build -t gaga5lala/fukuball-jieba-demo:$version .
script:
  - docker images gaga5lala/fukuball-jieba-demo
